### ISSUE TITLE
sql语句中某存储过程运行问题

### ISSUE THREAD

**Issue by NeiFeiTiii** [TuTouBird/MySQL-Experiment#2]
实验七的第六个，即proc5，当我将该仓库创建过程的代码拷贝运行时，会运行很久，不给出完成消息，是为什么呢？
另附我所写创建proc5语句：
CREATE PROCEDURE proc5(IN InputYear INT)
BEGIN
    DECLARE done int DEFAULT 1;
    DECLARE orderKEY INT;
    DECLARE total_Price DECIMAL(20,2);
    
    DECLARE find_cursor CURSOR FOR 
      SELECT orders.orderkey, SUM(extendedprice * (1 - discount) * (1 + tax))
      FROM lineitem, orders
      WHERE lineitem.orderkey = orders.orderkey AND YEAR(orderdate) = InputYear
      GROUP BY orders.orderkey;
    
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 0;
    
    OPEN find_cursor;
    
    loopbegin: WHILE done DO
      FETCH find_cursor INTO orderKEY, total_Price;
      IF done = 0 THEN
        LEAVE loopbegin;
      END IF;
      UPDATE orders SET totalprice = total_Price WHERE orderkey = orderKEY;
    END WHILE loopbegin;
  
    CLOSE find_cursor; 
      
END;

**Comment by NeiFeiTiii** [comment]
另外，在运行900s+之后，终于运行成功了。也许这个过程或者叫函数，运行就是很慢吧。

**Comment by TuTouBird** [comment]
首先感谢提出问题，运行确实存在问题，迟迟不结束。我把所有操作都集中到循环里面的update语句中，可读性差且存在逻辑问题。附我的修改版（实测3秒结束运行）：
create procedure proc5(in o_year int)
begin
    declare o_key int;
    declare t_price decimal(10,2);
    declare u_cursor cursor for select order_key from orders where year(order_date) = o_year;
    declare exit handler for not found close u_cursor;

    open u_cursor;
    while true do
        fetch u_cursor into o_key;
        select sum(extended_price * (1 - discount) * (1 + tax)) into t_price from line_item where order_key = o_key;
        update orders set total_price = t_price where order_key = o_key;
        end while;
end;

call proc5(2021);

**Comment by TuTouBird** [comment]
逻辑是相同的，只不过实现方式略有差异

**Comment by NeiFeiTiii** [comment]
> 逻辑是相同的，只不过实现方式略有差异

可以的，验证通过
